apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: compuslink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          # Remplacez par votre vrai nom d'image une fois pushée sur votre registre Docker
          image: compuslink/eureka-server:latest 
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: compuslink
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka