apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: compuslink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: compuslink/user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/compuslink_users"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: compuslink-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: compuslink-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: compuslink-secrets
                  key: jwt-secret
            - name: EUREKA_URI
              valueFrom:
                configMapKeyRef:
                  name: compuslink-config
                  key: EUREKA_URI
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: compuslink-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: compuslink-secrets
                  key: google-client-secret
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: compuslink-config
                  key: FRONTEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: compuslink
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: user-service